[project]
name = "gedinfo"
version = "0.12.3"
requires-python = ">=3.10"
description = "GEDCOM query utility"
dependencies = ["faker"]

[tool.setuptools]
packages = {find = {where = ["."]}}

[tool.setuptools.package-data]
gedinfo = ["data/*.txt"]

[project.optional-dependencies]
dev = ["pytest", "pytest-cov", "ruff", "black"]

[project.entry-points."console_scripts"]
gedinfo = "gedinfo.cli:main"

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "--tb=short"
